# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-03-03 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=200)),
                ('frequency', models.PositiveIntegerField()),
                ('assetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hkmanagement.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfAllocation', models.DateTimeField(default=django.utils.timezone.now)),
                ('taskToBePerformedBy', models.DateTimeField()),
                ('assetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hkmanagement.Asset')),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hkmanagement.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='workerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hkmanagement.Worker'),
        ),
    ]
