# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-03-03 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import hkmanagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('hkmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[(hkmanagement.models.FrequencyChoice('daily'), 'daily'), (hkmanagement.models.FrequencyChoice('hourly'), 'hourly'), (hkmanagement.models.FrequencyChoice('monthly'), 'monthly'), (hkmanagement.models.FrequencyChoice('weekly'), 'weekly'), (hkmanagement.models.FrequencyChoice('yearly'), 'yearly')], max_length=10),
        ),
    ]
